site_name: Requisitos Minecraft

repo_name: "Requisitos Minecraft"
repo_url: "https://github.com/reqMinecraft2024/Requisitos-Minecraft"

theme:
  name: material

  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: black

    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
      primary: black

  logo: assets/imgs/logo-minecraft.png
  favicon: assets/imgs/icone.png

extra_css:
  - assets/css/style.css

nav:
  - Início: index.md
  - Pré-Rastreabilidade:
    - Visão Geral: pre-rastreabilidade/visao-geral.md
    - Brainstorming: pre-rastreabilidade/Brainstorming.md
    - MoSCoW: pre-rastreabilidade/Moscow.md
    - Introspecção: pre-rastreabilidade/Introspeccao.md
    - Rich Picture: pre-rastreabilidade/Rich Picture.md
  - Modelagem:
    - Léxico: modelagem/lexico.md
    - Personas: modelagem/personas.md
    - Cenários: modelagem/cenarios.md

markdown_extensions:
  - attr_list
  - md_in_html
