site_name: Requisitos Minecraft

repo_name: "Requisitos Minecraft"
repo_url: "https://github.com/reqMinecraft2024/Requisitos-Minecraft"

theme:
  name: material

  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: black

    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
      primary: black

  logo: assets/imgs/logo-minecraft.png
  favicon: assets/imgs/icone.png

extra_css:
  - assets/css/style.css

nav:
  - Início: index.md
  - Visão Geral: visao-geral.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/Rich Picture.md
    - Argumentação: pre-rastreabilidade/argumentacao.md
  - Elicitações:
    - Análise de Protocolo: Elicitacoes/AnaliseProtocolo.md
    - Brainstorming: Elicitacoes/Brainstorming.md
    - MoSCoW: Elicitacoes/Moscow.md
    - Introspecção: Elicitacoes/Introspeccao.md
    - SWOT: Elicitacoes/SWOT.md
    - Questionários e pesquisas: Elicitacoes/questionarios-e-pesquisas.md
    - Requisitos não funcionais: Elicitacoes/requisitos-nao-funcionais.md
  - Modelagem:
    - Léxico: modelagem/lexico.md
    - Personas: modelagem/personas.md
    - Cenários: modelagem/cenarios.md
    - Epics: modelagem/Epics.md
    - Casos de uso: modelagem/casos-de-uso.md
    - Especificações Suplementares: modelagem/especificacaoSuplementar.md
    - Backlog do Produto: modelagem/backlog.md
    - NFR: modelagem/NFR.md
  - Análise:
    - Inspeção Cenários: Analise/cenarios.md

  - Reuniões:
    - Ata do dia 27/07/2024: reunioes/ata-24-07-24.md
    - Ata do dia 14/08/2024: reunioes/ata-14-08-24.md
  - Entregas:
    - Primeira entrega em vídeo: entregas/primeira-entrega.md
    - Segunda entrega em vídeo: entregas/segunda-entrega.md

markdown_extensions:
  - attr_list
  - md_in_html
